// js/constants/rendering.js

const DEFAULT_CANVAS_WIDTH = 600;
const DEFAULT_CANVAS_HEIGHT = 450;
const DEFAULT_CANVAS_ASPECT_RATIO = DEFAULT_CANVAS_HEIGHT / DEFAULT_CANVAS_WIDTH;
const ORIGIN_GLOW_DURATION_MS = 500;

const WEBGL_LINE_BATCH_LIMIT = 3500000;
const WEBGL_SUPERSAMPLE_FACTOR = 2.25;
const WEBGL_DOMAIN_COLOR_SUPERSAMPLE = 1.75;
const WEBGL_DOMAIN_COLOR_INTERACTION_SCALE = 1.2;
const WEBGL_DOMAIN_COLOR_STRESS_SCALE = 2.5;

const SPHERE_VIEW_RADIUS_FACTOR = 0.85;
const SPHERE_INITIAL_ROT_X = 0.4;
const SPHERE_INITIAL_ROT_Y = -0.6;
const SPHERE_GRID_LINES = 20;
const SPHERE_SENSITIVITY = 0.01;
const SPHERE_TEXTURE_AMBIENT_INTENSITY = 0.3;
const SPHERE_TEXTURE_DIFFUSE_INTENSITY = 0.7;
const SPHERE_TEXTURE_SPECULAR_INTENSITY = 0.6;
const SPHERE_TEXTURE_SHININESS_FACTOR = 32;
const SPHERE_BASE_SHADING_AMBIENT = 0.2;
const SPHERE_BASE_SHADING_DIFFUSE = 0.8;
const SPHERE_BASE_SHADING_COLOR = { r: 50, g: 60, b: 80 };
const SPHERE_LIGHT_DIRECTION_CAMERA = { x: 0.5, y: 0.5, z: 0.707 };
const SPHERE_GRID_LINE_MAX_WIDTH_W = 1.5;
const SPHERE_GRID_LINE_MAX_WIDTH_Z = 1.0;
const SPHERE_GRID_LINE_DEPTH_EFFECT = true;

const PARTICLE_RADIUS = 1.5;

const LINE_WIDTH_NORMAL = 1.5;
const LINE_WIDTH_THIN = 1.0;
const LINE_WIDTH_THICK = 2.5;